# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - keyboard-warriors-backend-wdocker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_22e40afbf234436db30d4aa14ff51c74 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1825fe43da6141e994a02077396ff0c4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        # =================================================================================
        # FIX: Force the image name to match the old placeholder
        # and point to the correct Dockerfile in the backend folder.
        # =================================================================================
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_22e40afbf234436db30d4aa14ff51c74 }}/appsvc/staticsite:${{ github.sha }}
        file: ./keyboard-warriors-backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'keyboard-warriors-backend-wdocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3bb5414383e54522a75597a972977e9d }}
        # NOTE: The image name here is already correct, so no change is needed.
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_22e40afbf234436db30d4aa14ff51c74 }}/appsvc/staticsite:${{ github.sha }}'

